name: Docker Test

on:
  workflow_run:
    workflows: ["Integration Tests"]
    branches: ["master", "develop"]
    types:
      - completed
jobs:
  docker-compose-up:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build and Start the Docker containers
        run: docker-compose up --build -d
      
      - name: Check if container is healthy
        run: docker-compose ps
      
      - name: Wait for container to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Wait for server to start
        run: curl --fail http://0.0.0.0:8000/api
