name: Docker Test

on:
  workflow_run:
    workflows: ["Integration Tests"]
    branches: ["master", "develop"]
    types:
      - completed
jobs:
  docker-compose-up:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Start the Docker containers
        run: docker-compose up --build -d
        env:
          DB_NAME: dbname
          DB_USER: user
          DB_PASSWORD: password
          DB_PORT: 5432
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_PASSWORD: adminpassword
          DJANGO_SUPERUSER_EMAIL: admin@example.com
          SECRET_KEY: your_secret_key
          ALLOWED_HOSTS: '*'
          DEBUG: 'True'
      
      - name: Check if container is healthy
        run: docker-compose ps
      
      - name: Wait for container to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Wait for server to start
        run: curl -s --fail http://0.0.0.0:8000/api > /dev/null

      - name: Shut down the Docker containers
        run: docker-compose down
