name: Docker Test

on:
  workflow_run:
    workflows: ["Integration Tests"]
    branches: ["master", "develop"]
    types:
      - completed

env:
  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_PASSWORD: admin
  DJANGO_SUPERUSER_EMAIL: admin@admin.com
  SECRET_KEY: django-insecure-*un^z^n1=hw(_c=4y3o65&i5sta%frz+s#53pqcopnisbn^2v-
  ALLOWED_HOSTS: "*"
  DEBUG: True
  DB_NAME: dbname
  DB_USER: user
  DB_PASSWORD: password
  DB_PORT: 5432
  DB_HOST: localhost

jobs:
  docker-compose-up:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables for debugging
        run: |
          echo "DB_NAME=${DB_NAME}"
          echo "DB_PORT=${DB_PORT}"
          echo "DB_USER=${DB_USER}"
          echo "DB_PASSWORD=${DB_PASSWORD}"
          echo "DB_HOST=${DB_HOST}"
          echo "SECRET_KEY=${SECRET_KEY}"
          echo "ALLOWED_HOSTS=${ALLOWED_HOSTS}"
          echo "DEBUG=${DEBUG}"
          echo "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
          echo "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
          echo "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
          
      - name: Build and Start the Docker containers
        run: docker-compose up --build -d
              
      - name: Check if container is healthy
        run: docker-compose ps
      
      - name: Wait for container to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Wait for server to start
        run: curl -s --fail http://0.0.0.0:8000/api > /dev/null

      - name: Shut down the Docker containers
        run: docker-compose down
