name: Unit Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pipx
      run: python -m pip install pipx

    - name: Ensure pipx binary path is on PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Poetry with pipx
      run: pipx install poetry

    - name: Install Dependencies
      run: poetry install

    - name: Run Tests
      run: poetry run task test
